language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE byob_test;' -U postgres
deploy:
  provider: heroku
  app: employment-data-be
  skip_cleanup: true
  api_key:
    secure: rnt+fKl+w75Y0TkWkNrztoL7ug/T/6VpxkE4ox7dj076/kmLg222X/e1b1IugQHYX+c63ux/tRemqOCpOcEgmbmQ9AnB6q77wjKkWIftdg/qjZ5EvET5mqUxux1K8zZsgd5hkyQhYoZQmPUie0R3SuXvaRdp/sbnnAL8utqlJkgRe88UaGCmoiueJ28WcibJLmnWECAdtg18u7y/PRX9HQGikMNj+b7FcnlV8wvKfXvgmlxf0iaPMRBkVPsDqR7f+cTmd0i1lmYLjHP/h2r3XO2ArCtu9nRfQUZ5Z255u34lyPHvYlP9Jl4OZl3lccUTBDOLK6GJGXtYnX1n3pEgk8jIlTvsu8+C4IAVBUstGnkADmo8NtlivkqRDF3yXmzAWplJUFJQmJ2V4YFF1+/l3S1ifdDv9gGwQrtMpRp1OrWmIqOr9JHkxhSCmz4xiaVm8Sd38r8SoBVWhWA8RUvSpVq+tZerzHayTdnmTe5XLPpbX46e6ea2QNNTExAHD1GRStfEWbkziF4QelqFf+KZvyNkjzvs9vrtm7bI8MT4lobpFAckfivNwSCQsvmxSX8aGiHWj3oJW6tmxVWjy+pGL9GO8hCrfRCPca2YBiteYWVCqPTkD3GQaW+I3WOsi8f6LBY6cuM8sDpFEzLUTZMnpv90sGxmGuemrIRikEtxzmo=
